services:
  - type: web
    name: eliyahu-chatbot-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
